### ISSUE TITLE
The Chapter 9 packages are missing

### ISSUE THREAD

**Issue by kazeno** [PacktPublishing/Learning-C-7-By-Developing-Games-with-Unity-2017-Third-Edition#1] opened 2018-01-09 22:15 UTC
The files Player.unitypackage and FloorShort.unitypackage, alluded to in Chapter 9 of the book, are missing both here and in the zip file hosted on the PacktPub website.

**Comment by ralph14** [comment] 2018-03-05 10:23
@kazeno 
Apologies for the inconvenience caused by this. These 3rd edition files have now been added to the code bundle for chapter 9 on both the Packt website and GitHub, so everything should be there as expected now!

**Comment by techsachinkumar** [comment] 2018-07-02 12:34
Closing as issue is rectified

**Closed as completed by techsachinkumar** 2018-07-02 12:34 UTC
